// Code generated by gocc; DO NOT EDIT.

package token

import (
	"fmt"
)

type Token struct {
	Type
	Lit []byte
	Pos
}

type Type int

const (
	INVALID Type = iota
	EOF
)

type Pos struct {
	Offset int
	Line   int
	Column int
}

func (p Pos) String() string {
	return fmt.Sprintf("Pos(offset=%d, line=%d, column=%d)", p.Offset, p.Line, p.Column)
}

type TokenMap struct {
	typeMap []string
	idMap   map[string]Type
}

func (m TokenMap) Id(tok Type) string {
	if int(tok) < len(m.typeMap) {
		return m.typeMap[tok]
	}
	return "unknown"
}

func (m TokenMap) Type(tok string) Type {
	if typ, exist := m.idMap[tok]; exist {
		return typ
	}
	return INVALID
}

func (m TokenMap) TokenString(tok *Token) string {
	//TODO: refactor to print pos & token string properly
	return fmt.Sprintf("%s(%d,%s)", m.Id(tok.Type), tok.Type, tok.Lit)
}

func (m TokenMap) StringType(typ Type) string {
	return fmt.Sprintf("%s(%d)", m.Id(typ), typ)
}

var TokMap = TokenMap{
	typeMap: []string{
		"INVALID",
		"$",
		"empty",
		"func",
		"ident",
		"lparen",
		"rparen",
		"if",
		"for",
		"let",
		"assign",
		"semicolon",
		"return",
		"elif",
		"else",
		"lbrace",
		"rbrace",
		"plus",
		"minus",
		"lt",
		"gt",
		"eq",
		"neq",
		"and",
		"or",
		"mul",
		"div",
		"string_literal",
		"int",
		"error",
		"true",
		"false",
		"comma",
	},

	idMap: map[string]Type{
		"INVALID":        0,
		"$":              1,
		"empty":          2,
		"func":           3,
		"ident":          4,
		"lparen":         5,
		"rparen":         6,
		"if":             7,
		"for":            8,
		"let":            9,
		"assign":         10,
		"semicolon":      11,
		"return":         12,
		"elif":           13,
		"else":           14,
		"lbrace":         15,
		"rbrace":         16,
		"plus":           17,
		"minus":          18,
		"lt":             19,
		"gt":             20,
		"eq":             21,
		"neq":            22,
		"and":            23,
		"or":             24,
		"mul":            25,
		"div":            26,
		"string_literal": 27,
		"int":            28,
		"error":          29,
		"true":           30,
		"false":          31,
		"comma":          32,
	},
}
